---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/

- Social:
    - X:
        - abbr: X
          href: https://x.com/
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
